apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pxc-client
  template:
    metadata:
      labels:
        name: pxc-client
    spec:
      containers:
      - name: pxc-client
        image: perconalab/backupjob-openshift:0.2.0
        imagePullPolicy: IfNotPresent
