apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: pxc
    cluster: custom
    component: custom-pxc-nodes
  name: custom-pxc-node
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: custom
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pxc
      cluster: custom
      component: custom-pxc-nodes
  serviceName: custom-pxc-nodes
  template:
    metadata:
      labels:
        app: pxc
        cluster: custom
        component: custom-pxc-nodes
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: another-node-label-key
                operator: In
                values:
                - another-node-label-value
            weight: 1
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/e2e-az-name
                operator: In
                values:
                - e2e-az1
                - e2e-az2
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - S1
            topologyKey: failure-domain.beta.kubernetes.io/zone
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: security
                  operator: In
                  values:
                  - S2
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: XTRABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: xtrabackup
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        - name: CLUSTERCHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: clustercheck
              name: my-cluster-secrets
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: node
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 600m
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datadir
        - mountPath: /etc/mysql/conf.d/
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 99
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: pxc
          optional: true
        name: config-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 6Gi
    status:
      phase: Pending
