apiVersion: pxc.percona.com/v1alpha1
kind: PerconaXtraDBCluster
metadata:
  name: scheduled-backup
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: perconalab/pxc-openshift:0.2.0
    volumeSpec:
      accessModes: [ "ReadWriteOnce" ]
      size: 1Gi
  proxysql:
    enabled: false
  pmm:
    enabled: false
  backup:
    image: perconalab/backupjob-openshift:0.2.0
    schedule:
      - name: each-min
        schedule: "* * * * *"
        keep: 3
        volume:
          size: 1Gi
      - name: sat-night-backup
        schedule: "0 0 * * 6"
        keep: 1
        volume:
          size: 1Gi
