apiVersion: pxc.percona.com/v1alpha1
kind: PerconaXtraDBCluster
metadata:
  name: scheduled-backup
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: perconalab/pxc-openshift:0.2.0
    volumeSpec:
      accessModes: [ "ReadWriteOnce" ]
      size: 1Gi
  proxysql:
    enabled: false
  pmm:
    enabled: false
