apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backup-client
  template:
    metadata:
      labels:
        name: backup-client
    spec:
      containers:
      - name: backup-client
        image: perconalab/backupjob-openshift:0.2.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /backup
          name: backup
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: some-name-xb-on-demand-backup1
